import Foundation

/// A scheduled pickup run at a court, stored at `games/{gameId}`.
///
/// The app's first piece of genuinely shared state — every other document in
/// Firestore has exactly one owner. Deliberately free of Firebase types, like
/// `Court` and `UserProfile`: `GameService` owns all encoding and writes
/// explicit field maps so server timestamps stay server-assigned.
nonisolated struct Game: Identifiable, Sendable, Codable, Hashable {
    /// Lifecycle of a run. `open` and `full` are **derived** from the roster
    /// rather than chosen — `firestore.rules` rejects a status that disagrees
    /// with `playerIds.count` against `maxPlayers`, so the two can't drift.
    ///
    /// `inProgress` and `completed` are declared because the schema owns them,
    /// but nothing writes them yet: there is no host-run controls UI, and the
    /// update rule only ever permits `open`/`full`. A run simply ages out of
    /// both lists once it's past `visibilityGrace`.
    enum Status: String, Sendable, Codable {
        case open
        case full
        case inProgress = "in_progress"
        case completed
    }

    /// Duplicates the Firestore document ID, the same way `UserProfile.id`
    /// duplicates the Auth uid. Unlike `users`, the ID here is generated by
    /// Firestore — it's mirrored into a field so the model decodes without a
    /// `@DocumentID` property wrapper, which would drag a Firebase type across
    /// the vendor boundary and into `Models/`.
    let id: String

    /// The organizer. Always present in `playerIds`, enforced server-side, so
    /// a run can never end up hosted by someone who isn't in it.
    let hostId: String

    /// A `Court.id` from the bundled dataset. Courts don't live in Firestore,
    /// so there's nothing to validate against server-side — the same caveat
    /// `UserProfile.homeCourtId` carries. A stale ID resolves to "Unknown
    /// court" in the UI rather than hiding the run.
    let courtId: String

    /// Client-supplied, so it's non-optional — unlike the server timestamps
    /// below, it can never read back as an unresolved sentinel.
    let scheduledTime: Date

    /// `true` = discoverable by anyone in range. `false` = invite-only, and
    /// visible only to players already on the roster.
    let isPublic: Bool

    let maxPlayers: Int

    let status: Status

    /// Confirmed players, `hostId` included. Never longer than `maxPlayers`.
    let playerIds: [String]

    /// Waitlist for a run that's already full. Always written — `[]` rather
    /// than absent — because the update rule diffs both arrays together, and a
    /// missing field would make that arithmetic conditional for no gain.
    let queuedPlayerIds: [String]

    /// Server-assigned at creation, immutable afterwards.
    let createdAt: Date?

    /// Server-assigned, refreshed on every write.
    let updatedAt: Date?
}

// MARK: - Rules of the game

nonisolated extension Game {
    /// Ten is 5-on-5, the default a pickup run is organized around.
    static let defaultMaxPlayers = 10

    /// Two is the smallest thing that's still a game. The upper bound is a
    /// sanity limit, not a basketball one. `firestore.rules` enforces the same
    /// range server-side; changing one without the other turns an out-of-range
    /// save into a `permission-denied`.
    static let maxPlayersRange: ClosedRange<Int> = 2...30

    /// How far ahead a run may be scheduled. Mirrored in the rules.
    static let schedulingWindow: TimeInterval = 30 * 24 * 60 * 60

    /// Minimum notice before tip-off.
    ///
    /// Exists to keep the client clear of the server's `scheduledTime >
    /// request.time` check: a run scheduled for "now" would race the round
    /// trip and come back as `permission-denied`, which reads like a rules
    /// deployment problem rather than a stale date picker.
    static let minimumLeadTime: TimeInterval = 5 * 60

    /// How long a run stays listed after its start time. Long enough that a
    /// run already underway is still joinable, short enough that yesterday's
    /// game isn't.
    static let visibilityGrace: TimeInterval = 3 * 60 * 60

    /// The single definition of `open` vs `full`. Used on the write path and
    /// mirrored in the rules, so a client that computes it differently is
    /// rejected rather than quietly storing a contradiction.
    static func status(playerCount: Int, maxPlayers: Int) -> Status {
        playerCount >= maxPlayers ? .full : .open
    }

    /// Coerces a requested roster size into the supported range, the way
    /// `UserProfile.validRadius` does for a stored radius. Used by the stepper
    /// so its buttons can't walk out of bounds; the write path *rejects* an
    /// out-of-range value rather than silently reshaping it.
    static func validMaxPlayers(_ requested: Int) -> Int {
        min(max(requested, maxPlayersRange.lowerBound), maxPlayersRange.upperBound)
    }

    /// Everything about a proposed run the client can check before writing it.
    ///
    /// Mirrors the create rule in `firestore.rules` one condition at a time, and
    /// is the **single** source of truth for whether a run is well-formed: the
    /// form's Save button, the inline hint, and `GameService.createGame` all
    /// call this rather than each carrying their own copy of the bounds. Pure
    /// and `now`-injectable, so every branch is testable without Firestore.
    ///
    /// Catching these here isn't defence in depth for its own sake — the rules
    /// reject the same values, but a rules rejection surfaces as
    /// `permission-denied`, which reads like an undeployed ruleset rather than
    /// a date two minutes in the past.
    ///
    /// - Returns: the first problem found, or `nil` when the run is valid.
    static func validate(
        courtId: String,
        scheduledTime: Date,
        maxPlayers: Int,
        now: Date = Date()
    ) -> GameError? {
        guard !courtId.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            return .invalidCourt
        }
        guard maxPlayersRange.contains(maxPlayers) else {
            return .invalidRoster
        }
        guard scheduledTime >= now.addingTimeInterval(minimumLeadTime) else {
            return .scheduleTooSoon
        }
        guard scheduledTime <= now.addingTimeInterval(schedulingWindow) else {
            return .scheduleTooFar
        }
        return nil
    }

    var isFull: Bool {
        playerIds.count >= maxPlayers
    }

    /// Never negative, even if a hand-edited document over-fills the roster.
    var openSlots: Int {
        max(0, maxPlayers - playerIds.count)
    }

    func isHost(_ userId: String?) -> Bool {
        guard let userId else { return false }
        return hostId == userId
    }

    func hasPlayer(_ userId: String?) -> Bool {
        guard let userId else { return false }
        return playerIds.contains(userId)
    }

    func hasWaitlisted(_ userId: String?) -> Bool {
        guard let userId else { return false }
        return queuedPlayerIds.contains(userId)
    }

    /// Whether a run still belongs in a list at `date`.
    ///
    /// The Firestore query applies the same cutoff, but it's evaluated when
    /// the listener attaches — a session left open for hours would otherwise
    /// keep showing a run that has since aged out. Re-applying it client-side
    /// on every rebuild is what actually retires the row.
    func isVisible(at date: Date) -> Bool {
        status != .completed && scheduledTime > date.addingTimeInterval(-Self.visibilityGrace)
    }

    /// The oldest `scheduledTime` still worth querying for, measured from
    /// `date`. Shared by both listeners so their cutoffs can't disagree.
    static func visibilityCutoff(from date: Date = Date()) -> Date {
        date.addingTimeInterval(-visibilityGrace)
    }
}

// MARK: - Presentation helpers

nonisolated extension Game {
    /// e.g. "4 / 10 players". Kept on the model rather than in a view so the
    /// queued and public cards can't render the roster two different ways.
    var rosterText: String {
        "\(playerIds.count) / \(maxPlayers) players"
    }

    var visibilityText: String {
        isPublic ? "Public" : "Invite only"
    }

    /// e.g. "Today · 6:30 PM", "Tomorrow · 9:00 AM", "Sat, Aug 15 · 6:30 PM".
    ///
    /// Relative for the two days a pickup run is usually organized within, and
    /// absolute past that — "in 3 days" reads as vaguer than the date it
    /// replaces. `relativeTo` is injectable so the boundary behaviour is
    /// testable without waiting for midnight.
    func scheduledText(relativeTo now: Date = Date()) -> String {
        let calendar = Calendar.current
        let time = Self.timeFormatter.string(from: scheduledTime)

        if calendar.isDate(scheduledTime, inSameDayAs: now) {
            return "Today · \(time)"
        }
        if let tomorrow = calendar.date(byAdding: .day, value: 1, to: now),
           calendar.isDate(scheduledTime, inSameDayAs: tomorrow) {
            return "Tomorrow · \(time)"
        }
        return "\(Self.dayFormatter.string(from: scheduledTime)) · \(time)"
    }

    private static let timeFormatter: DateFormatter = {
        let formatter = DateFormatter()
        formatter.dateStyle = .none
        formatter.timeStyle = .short
        return formatter
    }()

    private static let dayFormatter: DateFormatter = {
        let formatter = DateFormatter()
        formatter.setLocalizedDateFormatFromTemplate("EEEMMMd")
        return formatter
    }()
}

/// Domain-level failures for the `games` collection. `GameService` translates
/// Firestore's errors into these so no Firestore type escapes the service
/// layer, mirroring `UserProfileError`.
enum GameError: Error, Equatable {
    case notSignedIn
    /// No court attached to the run. Unreachable from the form, which is only
    /// ever opened from a specific court.
    case invalidCourt
    /// Roster size outside `Game.maxPlayersRange`.
    case invalidRoster
    /// Tip-off is in the past, or inside the minimum-notice window.
    case scheduleTooSoon
    /// Tip-off is beyond `Game.schedulingWindow`.
    case scheduleTooFar
    /// The run was deleted, or was never readable in the first place.
    case gameNotFound
    /// The run is full *and* its waitlist already holds the player, or it's
    /// no longer accepting anyone.
    case gameClosed
    /// Security rules rejected the operation. Whether that means "the ruleset
    /// isn't deployed" or "you genuinely may not do this" depends on which side
    /// it came from — see `GameService.message(for:whileDoing:context:)`.
    case permissionDenied
    /// Firestore's `failed-precondition`: a composite index the list query
    /// needs is missing, or still building. Both list queries need one.
    case indexRequired
    case network
    case unknown(String)
}
