import Foundation

/// A scheduled squad-vs-squad match, stored at `seasonGames/{gameId}`.
///
/// **The document that makes squad play legal.** Every other collection in this
/// app enforces "a client may only ever write its own membership", and this one
/// commits six people to a game — but it doesn't violate the rule, because it
/// names *squad IDs*, not player uids. The away leader writes one identifier
/// they already own, and the rules verify the rest against the home squad's own
/// ticket. Nobody's uid is written by anybody else anywhere in Seasons. See
/// `context/database/DATABASE_SCHEMA.md`.
///
/// Distinct from `Game`, and deliberately not a variant of it: a run has a host
/// and a roster of individuals, a season game has two squads and a result two
/// leaders had to agree on. Folding them together would mean one model where
/// half the fields are always absent.
///
/// Deliberately free of Firebase types, like every other model here.
nonisolated struct SeasonGame: Identifiable, Sendable, Codable, Hashable {
    /// Lifecycle of a match.
    ///
    /// `confirmed` and `disputed` are declared because the schema owns them and
    /// the derived-record query reads `confirmed` — but nothing writes either
    /// yet. Reporting is Phase 6. Declaring them now is what lets the record
    /// query be written today and simply return nothing, rather than being
    /// retrofitted later against a schema that changed underneath it.
    enum Status: String, Sendable, Codable, CaseIterable {
        case scheduled
        case cancelled
        /// Both leaders reported the same winner.
        case confirmed
        /// Both leaders reported, and disagreed. Counts for nobody.
        case disputed
    }

    /// Mirrors the document ID, generated by Firestore, following `Game.id`.
    let id: String

    let format: SquadFormat

    /// Copied from the tickets. The pool key both squads queued under.
    let region: String

    /// **Home is the squad whose ticket was claimed**, which is also whose
    /// court and window the match uses — the claim is what authorizes naming
    /// them, so everything scheduled is drawn from their offer.
    let homeSquadId: String

    /// The squad that won the claim and created this document.
    let awaySquadId: String

    /// `[home, away]`. The `array-contains` query field, and the reason one
    /// listener serves both squads.
    let squadIds: [String]

    /// Denormalized so the write rules need no `get()` to identify a leader —
    /// which is what keeps the cancel and report paths at zero document
    /// accesses instead of two.
    let homeLeaderId: String
    let awayLeaderId: String

    /// Denormalized so history survives a disbanded squad. Verified against
    /// `squads` at create, so they can't be invented.
    let homeSquadName: String
    let awaySquadName: String

    /// A `Court.id` from the bundled dataset. **Must be in the home ticket's
    /// `courtIds`**, enforced server-side — a modified client cannot schedule
    /// you somewhere you never said you'd go.
    let courtId: String

    /// Tip-off. Must fall inside the home ticket's window, enforced
    /// server-side.
    let scheduledTime: Date

    let status: Status

    /// Self-add only, both squads in one array. Phase 5.
    let arrivedPlayerIds: [String]

    /// The squad ID each leader says won. Each field is pinned to its own
    /// leader by the rules. Phase 6.
    let homeReport: String?
    let awayReport: String?

    let homeScore: Int?
    let awayScore: Int?

    /// The winning squad ID. Written **only** when both reports agree, which is
    /// what makes a record worth believing without a server. Phase 6.
    let result: String?

    let cancelledBySquadId: String?

    /// uid of the claiming leader.
    let createdBy: String

    let createdAt: Date?
    let updatedAt: Date?
    let confirmedAt: Date?
}

// MARK: - Reading a match

nonisolated extension SeasonGame {
    /// How long after tip-off a match stays on game day before it reads as
    /// history. The same shape `Game.visibilityGrace` uses, sized to a 3v3 plus
    /// the time it takes to argue about the score.
    static let visibilityGrace: TimeInterval = 3 * 60 * 60

    /// When the result prompt is worth showing — the T+90 prompt.
    static let reportingDelay: TimeInterval = 90 * 60

    var isScheduled: Bool { status == .scheduled }

    /// Whether this match still belongs on game day rather than in history.
    func isUpcoming(at now: Date) -> Bool {
        status == .scheduled && scheduledTime.addingTimeInterval(Self.visibilityGrace) > now
    }

    /// The other squad's ID, from `squadId`'s point of view. `nil` when the
    /// squad isn't in this match at all, which is a caller error rather than a
    /// state — the listener only ever delivers matches you're in.
    func opponentSquadId(of squadId: String) -> String? {
        switch squadId {
        case homeSquadId: return awaySquadId
        case awaySquadId: return homeSquadId
        default: return nil
        }
    }

    func opponentName(of squadId: String) -> String? {
        switch squadId {
        case homeSquadId: return awaySquadName
        case awaySquadId: return homeSquadName
        default: return nil
        }
    }

    func name(of squadId: String) -> String? {
        switch squadId {
        case homeSquadId: return homeSquadName
        case awaySquadId: return awaySquadName
        default: return nil
        }
    }

    func isHome(_ squadId: String) -> Bool { squadId == homeSquadId }

    func includes(squadId: String) -> Bool { squadIds.contains(squadId) }

    /// Whether `uid` may cancel this match. **Either leader**, and only while
    /// it's still scheduled — a match nobody could call off would sit on both
    /// squads' home screens forever, the same argument `games` makes for
    /// cancellation.
    func canCancel(uid: String) -> Bool {
        status == .scheduled && (uid == homeLeaderId || uid == awayLeaderId)
    }

    /// The squad `uid` leads in this match, if either.
    func ledSquadId(for uid: String) -> String? {
        if uid == homeLeaderId { return homeSquadId }
        if uid == awayLeaderId { return awaySquadId }
        return nil
    }

    func hasArrived(_ uid: String) -> Bool { arrivedPlayerIds.contains(uid) }
}

// MARK: - The record, which is a query rather than a field

nonisolated extension SeasonGame {
    /// A squad's win-loss record over confirmed matches.
    ///
    /// **This is the record of truth**, and it is arithmetic over documents two
    /// different leaders had to agree on rather than a counter a client could
    /// type. `squads` deliberately has no `wins`/`losses` field, on purpose.
    ///
    /// Until Phase 6 confirms anything this returns `(0, 0)` for everybody,
    /// which is correct rather than merely tolerable —
    /// `MatchTicket.winPercentage` reads an unplayed squad as 0.5, not as a
    /// squad that loses everything. Writing the derivation now is what stops a
    /// ticket from hardcoding zeros and then silently staying at zero after
    /// Phase 6 ships, with nothing failing to say so.
    static func record(for squadId: String, in games: [SeasonGame]) -> Record {
        var wins = 0
        var losses = 0

        for game in games {
            // Only `confirmed` counts. Disputed and cancelled matches are
            // structurally excluded because they never reach it.
            guard game.status == .confirmed, let result = game.result else { continue }
            guard game.includes(squadId: squadId) else { continue }

            if result == squadId {
                wins += 1
            } else {
                losses += 1
            }
        }

        return Record(wins: wins, losses: losses)
    }

    /// The last `limit` results for a squad, most recent first — the form
    /// guide. Cheapest possible way to make a record feel like a season rather
    /// than two integers.
    static func form(
        for squadId: String,
        in games: [SeasonGame],
        limit: Int = 5
    ) -> [Outcome] {
        games
            .filter { $0.status == .confirmed && $0.result != nil && $0.includes(squadId: squadId) }
            .sorted { $0.scheduledTime > $1.scheduledTime }
            .prefix(limit)
            .map { $0.result == squadId ? .win : .loss }
    }

    enum Outcome: String, Sendable, Equatable {
        case win = "W"
        case loss = "L"
    }

    struct Record: Sendable, Equatable {
        let wins: Int
        let losses: Int

        var played: Int { wins + losses }
        var isUnplayed: Bool { played == 0 }

        /// `0.5` for a squad that hasn't played, matching
        /// `MatchTicket.winPercentage` — treating "no record" as "loses
        /// everything" would rank every new squad against the worst opponents
        /// in the pool.
        var winPercentage: Double {
            guard played > 0 else { return 0.5 }
            return Double(wins) / Double(played)
        }

        var displayText: String { "\(wins)–\(losses)" }
    }
}

// MARK: - Reporting, and why a record is trustworthy

nonisolated extension SeasonGame {
    /// Which of the two report fields a leader owns.
    ///
    /// The raw value is the Firestore field name because that is the only thing
    /// this type is ever used for — picking one of two keys in a write map, and
    /// naming which lane the rules will hold the caller to.
    enum ReportField: String, Sendable, Equatable {
        case home = "homeReport"
        case away = "awayReport"
    }

    /// What a pair of reports means.
    ///
    /// **Derived, never chosen** — the same principle `Game.status` follows, and
    /// the rules compute this identically. The client deriving it too is what
    /// lets a report write be checked before it is sent, and what makes a
    /// `permission-denied` on one mean the state moved rather than the rules
    /// disagreeing.
    enum ReportOutcome: Sendable, Equatable {
        /// Fewer than two reports in. The match stays `scheduled`.
        case awaitingReport
        /// Both leaders reported, and named different winners. Counts for
        /// nobody, and either of them may re-report to resolve it.
        case disputed
        /// Both leaders reported the same winner. Carries the winning squad ID.
        case confirmed(String)

        var status: Status {
            switch self {
            case .awaitingReport: return .scheduled
            case .disputed:       return .disputed
            case .confirmed:      return .confirmed
            }
        }

        /// The winning squad ID, and `nil` for every state that isn't a
        /// confirmed one — which is exactly the rule the record query reads.
        var result: String? {
            guard case .confirmed(let squadId) = self else { return nil }
            return squadId
        }
    }

    /// The two reports, resolved.
    ///
    /// This is the whole of mutual confirmation as arithmetic: agreement
    /// confirms, disagreement disputes, and one report on its own settles
    /// nothing. Forging a win takes two colluding squads rather than one lying
    /// client — not cryptographic integrity, and the plan doesn't claim it is.
    static func outcome(homeReport: String?, awayReport: String?) -> ReportOutcome {
        guard let homeReport, let awayReport else { return .awaitingReport }
        return homeReport == awayReport ? .confirmed(homeReport) : .disputed
    }

    var reportOutcome: ReportOutcome {
        Self.outcome(homeReport: homeReport, awayReport: awayReport)
    }

    /// The statuses a report may be written from.
    ///
    /// `disputed` is here because the designed way out of a disagreement is a
    /// leader re-entering their own report — a rule that only permitted
    /// *absent → present* would make the design's own recovery path
    /// unreachable.
    ///
    /// `confirmed` is deliberately **not** here. A leader able to re-report a
    /// match both sides already agreed on could turn their own loss back into a
    /// dispute unilaterally, which is weaker than the rec-league scoresheet
    /// standard the design claims to meet.
    var isReportable: Bool {
        status == .scheduled || status == .disputed
    }

    /// Which report field `uid` owns here, if either. The rules pin the same
    /// pairing off the denormalized leader IDs.
    func reportField(for uid: String) -> ReportField? {
        if uid == homeLeaderId { return .home }
        if uid == awayLeaderId { return .away }
        return nil
    }

    /// What `uid` has already said won, if they've reported.
    func report(by uid: String) -> String? {
        switch reportField(for: uid) {
        case .home: return homeReport
        case .away: return awayReport
        case nil:   return nil
        }
    }

    /// The other leader's standing report, from `uid`'s point of view.
    func opponentReport(by uid: String) -> String? {
        switch reportField(for: uid) {
        case .home: return awayReport
        case .away: return homeReport
        case nil:   return nil
        }
    }

    /// Whether `uid` may report on this match right now.
    ///
    /// Mirrors the rule's own three preconditions, including the `now` one:
    /// a match cannot be reported before it has been played, which the rules
    /// check as `request.time >= scheduledTime`.
    func canReport(uid: String, at now: Date) -> Bool {
        isReportable && reportField(for: uid) != nil && now >= scheduledTime
    }

    /// Everything about a report the client can check before writing it,
    /// mirroring the reporting rule one condition at a time — the shape
    /// `validate(homeTicket:...)` above already uses.
    ///
    /// - Returns: the first problem found, or `nil` when the report is valid.
    func validateReport(
        winner winningSquadId: String,
        by uid: String,
        now: Date = Date()
    ) -> SeasonGameError? {
        guard reportField(for: uid) != nil else { return .notLeader }
        guard isReportable else { return .notScheduled }
        guard now >= scheduledTime else { return .notPlayed }
        guard includes(squadId: winningSquadId) else { return .unknownWinner }
        return nil
    }

    /// The document state a report write produces.
    ///
    /// Pure, and takes the two standing reports rather than reading them off
    /// `self`, because the transaction that performs the write reads them from
    /// its own snapshot — the only view of the document guaranteed current. The
    /// stale copy on `self` is what the race in the plain-write shape is made
    /// of.
    static func reportWrite(
        field: ReportField,
        winner winningSquadId: String,
        homeScore: Int?,
        awayScore: Int?,
        standingHomeReport: String?,
        standingAwayReport: String?
    ) -> ReportWrite {
        let home = field == .home ? winningSquadId : standingHomeReport
        let away = field == .away ? winningSquadId : standingAwayReport

        return ReportWrite(
            field: field,
            winningSquadId: winningSquadId,
            homeScore: homeScore,
            awayScore: awayScore,
            outcome: outcome(homeReport: home, awayReport: away)
        )
    }

    /// One leader's report, and what the document reads as once it lands.
    struct ReportWrite: Sendable, Equatable {
        let field: ReportField
        let winningSquadId: String
        let homeScore: Int?
        let awayScore: Int?
        let outcome: ReportOutcome

        var status: Status { outcome.status }

        /// Set only when this write completes a matching pair — which is the
        /// only circumstance the rules accept a `result` at all.
        var result: String? { outcome.result }

        var confirms: Bool { outcome.result != nil }
    }
}

// MARK: - Creating a match

nonisolated extension SeasonGame {
    /// Everything about a proposed match the client can check before writing
    /// it, mirroring the create rule one condition at a time — the shape
    /// `Game.validate`, `Squad.validate` and `MatchTicket.validate` already
    /// use.
    ///
    /// The client checking first is what makes a `permission-denied` on this
    /// write *mean* something: the server rejected what the client believed was
    /// legal, which is stale state or a real authorization bug, never a
    /// deployment problem.
    ///
    /// - Returns: the first problem found, or `nil` when the match is valid.
    static func validate(
        homeTicket: MatchTicket,
        awayTicket: MatchTicket,
        courtId: String,
        scheduledTime: Date,
        now: Date = Date()
    ) -> SeasonGameError? {
        guard homeTicket.squadId != awayTicket.squadId else { return .sameSquad }
        guard !homeTicket.sharesPlayer(with: awayTicket) else { return .sharedPlayer }
        guard homeTicket.format == awayTicket.format else { return .formatMismatch }
        guard homeTicket.region == awayTicket.region else { return .regionMismatch }

        // The court and time have to be ones the *home* squad actually offered,
        // because the home ticket is what the rules check against. Deriving
        // them from anywhere else produces a legal-looking match the server
        // refuses.
        guard homeTicket.courtIds.contains(courtId) else { return .courtNotOffered }
        guard scheduledTime >= homeTicket.windowStart,
              scheduledTime <= homeTicket.windowEnd else { return .timeOutsideWindow }
        guard scheduledTime > now.addingTimeInterval(Game.minimumLeadTime) else {
            return .scheduleTooSoon
        }

        return nil
    }

    /// The two squad IDs in the order the rules require: `[home, away]`.
    ///
    /// Built here rather than at each call site because the create rule asserts
    /// `squadIds == [homeSquadId, awaySquadId]` **exactly** — order included —
    /// and an array assembled in the other order is a `permission-denied` with
    /// no obvious cause.
    static func squadIds(home: String, away: String) -> [String] {
        [home, away]
    }
}

/// Domain-level failures for the `seasonGames` collection.
///
/// Separate from `MatchTicketError` because the two describe different objects:
/// a ticket is an offer and a match is a commitment, and folding them together
/// would give the game-day screen a vocabulary full of queueing states it can't
/// reach.
nonisolated enum SeasonGameError: Error, Equatable {
    case notSignedIn
    /// A squad cannot play itself.
    case sameSquad
    /// The two rosters overlap — a person cannot play themselves.
    case sharedPlayer
    case formatMismatch
    case regionMismatch
    /// The chosen court isn't on the home ticket's list. The rules refuse it.
    case courtNotOffered
    /// Tip-off falls outside the home ticket's window. The rules refuse it.
    case timeOutsideWindow
    case scheduleTooSoon
    /// The claim went stale, or somebody else's game landed first.
    case claimExpired
    case gameNotFound
    /// Only a leader of one of the two squads may do that.
    case notLeader
    /// The match is already cancelled, confirmed or disputed.
    case notScheduled
    /// Tip-off hasn't happened yet — a match can't be reported before it's
    /// played, and the rules refuse it too.
    case notPlayed
    /// The squad named as the winner isn't in this match.
    case unknownWinner
    case permissionDenied
    case indexRequired
    case network
    case unknown(String)
}
