import Foundation

/// A named team of players who queue together for season matches, stored at
/// `squads/{squadId}`.
///
/// The third piece of shared, multi-user state after `games` and
/// `friendships`, and the first one whose *subject* is a group rather than a
/// person or a pair. That distinction is what makes squad-vs-squad play legal
/// under the app's central rule — a client may only ever write its own
/// membership. A match names two **squad IDs**, so a leader commits three
/// people by writing one identifier they already own, and nobody's uid is ever
/// written by anybody else. See `context/plans/SEASONS.md` §0.3.
///
/// **No `wins` / `losses` here, deliberately.** A record is derived from
/// confirmed `seasonGames`, not stored on the squad — a counter on a document
/// you control is a number you can type. See the plan's §1.1; the cost is one
/// extra query to show an opponent's record.
///
/// Deliberately free of Firebase types, like `Game` and `Friendship`:
/// `SquadService` owns all encoding and writes explicit field maps so server
/// timestamps stay server-assigned. Don't hand this struct to `setData(from:)`.
nonisolated struct Squad: Identifiable, Sendable, Codable, Hashable {
    /// Duplicates the Firestore document ID, the same way `Game.id` does —
    /// mirrored into a field so the model decodes without a `@DocumentID`
    /// property wrapper, which would drag a Firebase type into `Models/`.
    ///
    /// Unlike `Friendship.id`, this one is *stored*: a squad ID is generated by
    /// Firestore and there's nothing else to recover it from.
    let id: String

    /// 3–24 characters. Bounds mirrored in `firestore.rules`.
    let name: String

    /// `name` lowercased, the search key — mirrors `UserProfile.userNameLower`.
    /// Non-optional here because there are no pre-existing squads to backfill.
    let nameLower: String

    /// The account that created the squad. Always present in `memberIds`,
    /// enforced server-side, so a squad can never end up led by someone who
    /// isn't in it — the same invariant `games` holds for its host.
    let leaderId: String

    /// Everyone on the squad, `leaderId` included. Bounded by
    /// `format.maxRoster`.
    ///
    /// Required, not defaulted: a document without it fails to decode rather
    /// than reading back as an empty squad. A silent `[]` would render a squad
    /// with no members and let the roster ceiling be computed against a roster
    /// that isn't the stored one.
    let memberIds: [String]

    /// What's being played. Carried from day one so adding 1v1 and 5v5 is an
    /// allowlist entry plus a roster bound, not a migration.
    let format: SquadFormat

    /// SF Symbol name for the crest, from `Squad.iconKeys`. Allowlisted in the
    /// rules for the same reason `users`' key allowlist exists: this document
    /// is readable by every signed-in account, so an arbitrary client-chosen
    /// string here is a string everyone else renders.
    let iconKey: String

    /// Palette key for the crest, from `Squad.colorKeys`. Resolved to a real
    /// colour in `Theme.swift`, never stored as one — a stored hex would
    /// bypass the appearance-aware colour roles entirely.
    let colorKey: String

    /// The matchmaking pool this squad belongs to: `Court.city` of the
    /// leader's nearest court at creation time.
    ///
    /// A placeholder with a known successor — `plans/SCALE_UP.md` S1.1 defines
    /// a real region key for multi-city delivery, and when it ships this field
    /// becomes that key with the pool query unchanged. Deliberately unbounded
    /// in the rules beyond "non-empty string": bounding the length of a
    /// placeholder would mirror a constant that's already scheduled to change.
    let region: String

    /// Server-assigned at creation, immutable afterwards.
    let createdAt: Date?

    /// Server-assigned, refreshed on every leader edit and roster change.
    let updatedAt: Date?
}

// MARK: - Format

/// What a squad plays, and how many people that takes.
///
/// All three cases are declared because the schema carries `format` from day
/// one, but only `available` may actually be created — `firestore.rules`
/// allowlists exactly that set, and `FirestoreRulesParityTests` fails if the
/// two copies drift. The other two render as "soon" in the create sheet.
nonisolated enum SquadFormat: String, Sendable, Codable, Hashable, CaseIterable {
    case oneVOne = "1v1"
    case threeVThree = "3v3"
    case fiveVFive = "5v5"

    /// The formats a squad can be created with today. Mirrored in the rules'
    /// `format in [...]` allowlist.
    ///
    /// Adding a format means an entry here, an entry in the rules' allowlist,
    /// and a branch in the rules' `maxRoster()` — the parity tests fail if any
    /// one of the three is missed.
    static let available: [SquadFormat] = [.threeVThree]

    /// Players on the court per side.
    var playersPerSide: Int {
        switch self {
        case .oneVOne:     return 1
        case .threeVThree: return 3
        case .fiveVFive:   return 5
        }
    }

    /// The roster ceiling — a side plus the same number again in substitutes,
    /// which is what a pickup squad realistically carries. Mirrored in the
    /// rules' `maxRoster()`.
    var maxRoster: Int {
        playersPerSide * 2
    }

    /// How long a match of this format is scheduled to take. Used by Phase 3's
    /// window-overlap rule; declared here so the two can't disagree.
    var duration: TimeInterval {
        60 * 60
    }

    var displayName: String { rawValue }

    var isAvailable: Bool { Self.available.contains(self) }
}

// MARK: - Rules of a squad

nonisolated extension Squad {
    /// A name short enough to sit beside a 24pt crest and long enough to be a
    /// name. `firestore.rules` enforces the same range server-side; changing
    /// one without the other turns a legal name into a `permission-denied`.
    static let nameLengthRange: ClosedRange<Int> = 3...24

    /// The crest glyphs a squad may choose. Allowlisted in the rules.
    ///
    /// Ordered as the create sheet's grid reads, not alphabetically — the
    /// first entry is the default, and it's the one this app is about.
    static let iconKeys: [String] = [
        "basketball.fill",
        "flame.fill",
        "bolt.fill",
        "crown.fill",
        "shield.fill",
        "star.fill",
        "hare.fill",
        "tortoise.fill",
        "pawprint.fill",
        "bird.fill",
        "mountain.2.fill",
        "hexagon.fill",
    ]

    /// The crest fills a squad may choose. Allowlisted in the rules, resolved
    /// to appearance-aware colours in `Theme.swift`.
    static let colorKeys: [String] = [
        "orange",
        "red",
        "pink",
        "purple",
        "blue",
        "teal",
        "green",
        "gold",
    ]

    static var defaultIconKey: String { iconKeys[0] }
    static var defaultColorKey: String { colorKeys[0] }

    /// What a stored `nameLower` holds, and what a typed prefix is reduced to
    /// before searching — mirrors `UserProfile.searchKey` so the two search
    /// keys in the app are built the same way.
    static func searchKey(_ raw: String) -> String {
        raw.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
    }

    /// The name as it will actually be stored: trimmed, never reshaped
    /// further. Length is *rejected* out of range rather than truncated —
    /// silently storing 24 characters of a 30-character name stores something
    /// nobody chose.
    static func normalizedName(_ raw: String) -> String {
        raw.trimmingCharacters(in: .whitespacesAndNewlines)
    }

    /// Everything about a proposed squad the client can check before writing
    /// it, mirroring the create rule one condition at a time.
    ///
    /// The single source of truth for whether a squad is well-formed: the
    /// create sheet's Save button, its inline hint, and
    /// `SquadService.createSquad` all call this rather than each carrying
    /// their own copy of the bounds — the shape `Game.validate` established.
    ///
    /// Catching these here isn't defence in depth for its own sake: the rules
    /// reject the same values, but a rules rejection surfaces as
    /// `permission-denied`, which reads like an undeployed ruleset rather than
    /// a two-character name.
    ///
    /// - Returns: the first problem found, or `nil` when the squad is valid.
    static func validate(
        name: String,
        format: SquadFormat,
        iconKey: String,
        colorKey: String,
        region: String
    ) -> SquadError? {
        if let problem = validate(name: name) { return problem }
        guard format.isAvailable else { return .unsupportedFormat }
        guard iconKeys.contains(iconKey) else { return .unknownIcon }
        guard colorKeys.contains(colorKey) else { return .unknownColor }
        guard !region.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            return .missingRegion
        }
        return nil
    }

    /// The name check on its own, so the create sheet can hint about a name
    /// while the icon grid is still untouched.
    static func validate(name raw: String) -> SquadError? {
        let name = normalizedName(raw)
        guard name.count >= nameLengthRange.lowerBound else { return .nameTooShort }
        guard name.count <= nameLengthRange.upperBound else { return .nameTooLong }
        return nil
    }

    // MARK: Roster

    var isFull: Bool {
        memberIds.count >= format.maxRoster
    }

    /// Never negative, even if a hand-edited document over-fills the roster.
    var openSlots: Int {
        max(0, format.maxRoster - memberIds.count)
    }

    func isLeader(_ userId: String?) -> Bool {
        guard let userId else { return false }
        return leaderId == userId
    }

    func hasMember(_ userId: String?) -> Bool {
        guard let userId else { return false }
        return memberIds.contains(userId)
    }

    /// Whether `userId` may leave under the rules' self-leave path. The leader
    /// can't — disbanding is their exit, the same way cancelling is a `games`
    /// host's.
    func canLeave(_ userId: String?) -> Bool {
        hasMember(userId) && !isLeader(userId)
    }

    /// e.g. "3 / 6 players". Kept on the model rather than in a view so the
    /// squad home and the detail screen can't render the roster two different
    /// ways — the role `Game.rosterText` already plays.
    var rosterText: String {
        "\(memberIds.count) / \(format.maxRoster) players"
    }

    // MARK: One squad per person

    /// Why the signed-in user may not join or create a squad right now, or
    /// `nil` when they may. **The one-squad-per-person rule**, in one place so
    /// `SquadService` (which enforces it) and `SquadViewModel` (which stops the
    /// UI offering what would be refused) can't disagree.
    ///
    /// **App-enforced only.** `firestore.rules` can't ask "which squads is this
    /// uid on" — rules can't query — so a modified client can still join a
    /// second squad. `MatchRules` skips a pairing of two squads that share a
    /// player, so an honest client never plays someone against themselves —
    /// but that is a filter in the client too, not a rule the server checks.
    ///
    /// - Parameters:
    ///   - squads: every squad the user is on, as `SquadService` carries them.
    ///   - haveLoaded: whether that list has been answered at all. Until then
    ///     an empty list means "unknown", not "on none", and a join let through
    ///     on it would be exactly the second squad the rule exists to stop.
    ///   - joining: the squad being joined, if it's an existing one. Excluded
    ///     from the check, so accepting a stale invite to a squad you're
    ///     already on stays the quiet no-op `SquadService.acceptInvite`
    ///     documents rather than becoming a refusal.
    ///
    /// Someone who joined two squads before this rule existed still has both,
    /// and is refused any third. The check is "any squad that isn't this
    /// one", so they can't use one of their two as cover for joining another.
    static func membershipBlock(
        among squads: [Squad],
        haveLoaded: Bool,
        viewedBy userId: String?,
        joining squadId: String? = nil
    ) -> SquadError? {
        guard haveLoaded else { return .squadsNotLoaded }

        guard let existing = squads.first(where: { $0.id != squadId }) else { return nil }

        return .alreadyOnASquad(name: existing.name, isLeader: existing.isLeader(userId))
    }
}

/// Domain-level failures for the `squads` and `squadInvites` collections.
/// `SquadService` translates Firestore's errors into these so no Firestore
/// type escapes the service layer, mirroring `GameError` and `FriendError`.
nonisolated enum SquadError: Error, Equatable {
    case notSignedIn
    /// Fewer than `Squad.nameLengthRange.lowerBound` characters after
    /// trimming.
    case nameTooShort
    case nameTooLong
    /// A format the schema declares but the rules don't yet allow — 1v1 and
    /// 5v5 today.
    case unsupportedFormat
    case unknownIcon
    case unknownColor
    /// No region could be derived, which happens when no court is in range.
    /// Never defaulted: a wrong region silently partitions the matchmaking
    /// pool into groups that can never see each other.
    case missingRegion
    /// The squad was disbanded between reading it and acting on it.
    case squadNotFound
    /// The invite was revoked or already consumed.
    case inviteNotFound
    /// The roster is at `format.maxRoster`.
    case squadFull
    /// Already on the roster — a duplicate tap from a stale screen.
    case alreadyMember
    /// Already on a *different* squad, and a person is on one at a time — see
    /// `Squad.membershipBlock`. Carries what the sentence needs, because the
    /// way out differs: a member leaves, a leader can only disband.
    case alreadyOnASquad(name: String, isLeader: Bool)
    /// The squads listener hasn't answered yet, so "on no squad" can't be told
    /// from "don't know". Refused rather than guessed, since a wrong guess is a
    /// second squad.
    case squadsNotLoaded
    /// The leader tried to leave their own squad. Disbanding is their exit.
    case leaderCannotLeave
    /// Only the leader may edit or invite. Caught client-side; the rules
    /// reject it too, but as `permission-denied`.
    case notLeader
    /// You can't invite yourself.
    case cannotInviteSelf
    /// Security rules rejected the operation. Whether that means "the ruleset
    /// isn't deployed" or "you genuinely may not do this" depends on which side
    /// it came from — see `SquadService.message(for:whileDoing:context:)`.
    case permissionDenied
    /// Firestore's `failed-precondition`: a composite index the query needs is
    /// missing or still building.
    case indexRequired
    case network
    case unknown(String)
}
